version: '3'

services:
    postgress:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server   #use the code to build the image from the server folder
        volumes: 
            - /app/node_modules #this is like a block, do not play with this folder at all costs inside the container
            - ./server:/app #copy everything inside the server directory to the /app "as we specified it in the WORKDIR inside the docker file" folder
        environment: #variablename=value
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
            
    worker:
        build: 
            dockerfile: dockerfile.dev
            context: ./Worker
        volumes:
            - /app/node_modules
            - ./worker:/app  
    nginx:
        restart: always #always start this service
        build: 
            dockerfile: dockerfile.dev
            context: ./nginx
        ports: #there is port mapping in nginx so externally map port 3050 to port 80 inside nginx container
            - '3000:80'
      



